### ISSUE TITLE
Error reported about `outs[i].reshape`

### ISSUE THREAD

**Issue by uxfion** [pengtougu/Push-Streaming#4]
## 关于outs[i].reshape的报错

作者您好，
我从github clone下你的代码，所有环境均已配置完成，但是运行单个推理文件`python v5_dnn.py`的时候会报错：

```
Traceback (most recent call last):
  File "D:\Lecter\Downloads\ml-proj\YOLO-Streaming\v5_dnn.py", line 118, in <module>
    yolonet.v5_inference(frame)
  File "D:\Lecter\Downloads\ml-proj\YOLO-Streaming\v5_dnn.py", line 38, in v5_inference
    outs = self.detect(frame)
  File "D:\Lecter\Downloads\ml-proj\YOLO-Streaming\v5_dnn.py", line 98, in detect
    outs[i] = outs[i].reshape(bs, self.na, self.no, ny, nx).transpose(0, 1, 3, 4, 2)
TypeError: 'tuple' object does not support item assignment
```

指向的是`v5_dnn.py`文件中：

```
        for i in range(self.nl):
            bs, _, ny, nx = outs[i].shape  # x(bs,255,20,20) to x(bs,3,20,20,85)
            # outs[i] = outs[i].view(bs, self.na, self.no, ny, nx).permute(0, 1, 3, 4, 2).contiguous()
            outs[i] = outs[i].reshape(bs, self.na, self.no, ny, nx).transpose(0, 1, 3, 4, 2)
            if self.grid[i].shape[2:4] != outs[i].shape[2:4]:
                self.grid[i] = self._make_grid(nx, ny)

            y = 1 / (1 + np.exp(-outs[i]))  ### sigmoid
            ###其实只需要对x,y,w,h做sigmoid变换的， 不过全做sigmoid变换对结果影响不大，因为sigmoid是单调递增函数，那么就不影响类别置信度的排序关系，因此不影响后面的NMS
            ###不过设断点查看类别置信度，都是负数，看来有必要做sigmoid变换把概率值强行拉回到0到1的区间内
            y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i]) * int(self.stride[i])
            y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
            z.append(y.reshape(bs, -1, self.no))

```

中的`outs[i] = outs[i].reshape(bs, self.na, self.no, ny, nx).transpose(0, 1, 3, 4, 2)`

报错类型为`TypeError: 'tuple' object does not support item assignment`

麻烦可以帮我看一下吗

**Comment by 961540897** [comment]
opencv版本的问题，改成4.4就行了，比如4.4.0.40
